server:
  port: 9000
logging:
  level:
    com:
      lens:
        packt:
          learnspringboot2:
            learnspringboot: DEBUG
endpoints:
  health:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
    metrics:
      enabled: true